# Generated by Django 5.0.6 on 2024-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_orders_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
